# basic info
title = 'Aditya Rathod'
baseURL = 'https://adibytes.dev'
languageCode = 'en-us'
theme = 'adi'
googleAnalytics = 'G-N0PPYCM4QZ'
disableHugoGeneratorInject = true
pluralizeListTitles = false

# author info
[params.author]
name = 'Aditya Rathod'

# theme params
[params]
description = 'Generalist software engineer driven by hard problems.'

# hero params
[params.hero]
description = [
    "Generalist software engineer driven by hard problems.",
    "Currently building geospatial infra for constrained environments.",
    "In my free time, I cook, travel, and [discover new music](https://www.last.fm/user/adibytes)."
]

[markup.goldmark.renderer]
unsafe = true
