# basic info
title = 'aditya'
baseURL = 'https://adityarathod.github.io'
languageCode = 'en-us'
theme = 'adi'
googleAnalytics = 'G-N0PPYCM4QZ'
disableHugoGeneratorInject = true
pluralizeListTitles = false

# author info
[author]
name = 'Aditya Rathod'

# theme params
[params]
description = 'Software engineer that loves building cool stuff with data and code.'

# hero params
[params.hero]
bigTitle = "👋 hi, i'm aditya."
description = [
    "I'm a software engineer with a focus on distributed systems and networks.",
    "In my free time, I learn guitar, cook, listen to [lots of music](https://www.last.fm/user/adibytes), and [feed the enemy team in League](https://na.op.gg/summoners/na/Dichotomous)."
]

[params.footer]
specialMessages = [
    "i hope i don't have to rewrite this again",
    "rfc 1925 section 2.8",
    "i feed on the 🙌 reactions by the senior engineers in slack when i post something useful",
    "oncall is like solo carrying in league",
    "E492: not an editor command: meow",
    "me (pressing random buttons to see what happens): \"yeah oncall is fun it's like an adventure\"",
    "i got gatos on my keyboard",
    "a big component of your job as an engineer is to push back against bad ideas",
    "the faang pm and faang engineer founder duo is unstoppable",
    "have you ever written a design doc for your design doc",
    "if err != nil {",
]
