# basic info
title = 'Aditya Rathod'
baseURL = 'https://adibytes.dev'
languageCode = 'en-us'
theme = 'adi'
googleAnalytics = 'G-N0PPYCM4QZ'
disableHugoGeneratorInject = true
pluralizeListTitles = false

# author info
[params.author]
name = 'Aditya Rathod'

# theme params
[params]
description = 'Software engineer with a focus on distributed systems and networks.'

# hero params
[params.hero]
description = [
    "I'm a software engineer with a focus on distributed systems and networks.",
    "I currently work on network-layer DDoS protection at AWS.",
    "In my free time, I cook, travel, and [discover new music](https://www.last.fm/user/adibytes)."
]

[markup.goldmark.renderer]
unsafe = true
